estore/estore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# link to store app urls as well as to where our media is kept
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

estore/store/urls.py
from django.urls import path
from . import views
from store.forms import LoginForm, SetPasswordForm, PasswordResetForm, PasswordChangeForm
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    # Home URL
    path('', views.home, name="home"),

    # Cart and Checkout URL
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:cart_id>/', views.remove_from_cart, name='remove-from-cart'),
    path('incr-cart/<int:cart_id>/', views.incr_cart_item, name='incr-cart'),
    path('decr-cart/<int:cart_id>/', views.decr_cart_item, name='decr-cart'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),

    # Products URL
    path('product/<slug:slug>/', views.detail, name='product-detail'),
    path('categories/', views.all_categories, name='all-categories'),
    path('<slug:slug>/', views.category_products, name='category-products'),
    path('shop/', views.shop, name='shop'),

    # Authentication URL
    path('accounts/register/', views.RegistrationView.as_view(), name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name='login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/add-address/', views.AddressView.as_view(), name='add-address'),
    path('accounts/remove-address/<int:id>/', views.remove_address, name='remove-address'),
    path('accounts/logout', auth_views.LogoutView.as_view(next_page='store:login'), name='logout'),

    path('accounts/password-change', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name='password-change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name='password-change-done'),

    path('accounts/password-reset', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset-done/'), name='password-reset'),
    path('accounts/password-reset-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_reset_done.html'), name='password-reset-done'),
    path('account/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete'), name='password-reset-confirm'),
    path('account/password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html')),
]

estore/store/forms.py
#from django.db import models
#from django.db.models import fields
#from django.forms import widgets
#from django.forms.fields import CharField
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from store.models import Address

# Registration Form to create/register a new user into the system
class RegistrationForm(UserCreationForm):
    email = forms.CharField(label="Email Address", required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email Address'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Confirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {'username' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Username'})}

# Login Form
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class' : 'form-control', 'autofocus' : True}))
    password = forms.CharField(label='Password', strip=False, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'autocomplete' : 'current-password'}))

# Set Password Form
class SetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="New Password", strip=False, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'autocomplete' : 'new-password'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label="Confirm Password", strip=False, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'autocomplete' : 'new-password'}))

# Password Reset Form (send confirmation to email)
class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254, widget=forms.EmailInput(attrs={'class' : 'form-control', 'autocomplete' : 'email'}))

# Password Change Form (requires old password)
class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Old Password", strip=False, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'auto-focus' : True, 'autocomplete' : 'current-password', 'placeholder' : 'Current Password'}))
    new_password1 = forms.CharField(label="New Password", strip=False, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'autocomplete' : 'new-password', 'placeholder' : 'New Password'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label="Confirm Password", strip=False, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'autocomplete' : 'new-password', 'placeholder' : 'Confirm Password'}))

# Address Form
class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['location', 'street_address', 'city', 'state']
        widgets = {
            'location' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Location Name'}),
            'street_address' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Street Address'}),
            'city' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'city'}),
            'state' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'state'}),
        }

estore/store/views.py
# from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Address, Category, Product, Cart, Order
from .forms import RegistrationForm, AddressForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Views - python functions which receive a web request and return a web response
#         (similar to Node.js's Express routers)


# Home Page
def home(request):
    # filter based on which categories and products are active AND marked to be featured on homepage
    # up to 3 categories and up to 8 products
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    context = {
        "categories" : categories,
        "products" : products,
    }
    return render(request, "store/index.html", context)

# Detail Page for a specific Product based on slug; also renders related products to the customer
def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    # related products are of the same category but not including the current product in detail
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)
    context = {
        "product" : product,
        "related_products" : related_products,
    }
    return render(request, "store/detail.html", context)

# Display all active categories in our eStore
def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, "store/categories.html", {'categories' : categories})

# Display all products of a specific category
def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)
    categories = Category.objects.filter(is_active=True)
    context = {
        "category" : category,
        "products" : products,
        "categories" : categories,
    }
    return render(request, "store/category_products.html", context)

# Authentication

# Register a new customer, class-based view
class RegistrationView(View):
    form_class = RegistrationForm()
    template_name = 'account/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            messages.success(request, "Welcome to the Club! Registration Successful.")
            form.save()
        return render(request, self.template_name, {'form' : form})

# View User Profile (must be logged in)
@login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, "account/profile.html", {'addresses' : addresses, 'orders' : orders})

# View User's Address Page (must be logged in)
@method_decorator(login_required, name='dispatch')
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, "account/add_address.html", {'form' : form})
    
    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            user = request.user
            location = form.cleaned_data['location']
            street_address = form.cleaned_data['street_address']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            address = Address(user=user, location=location, street_address=street_address, city=city, state=state)
            address.save()
            messages.success(request, "New Address Added Successfully")
        return redirect('store:profile')

# Remove an existing address from profile (must be logged in)
@login_required
def remove_address(request, id):
    to_remove = get_object_or_404(Address, user=request.user, id=id)
    to_remove.delete()
    messages.success(request, "Address Successfully Removed")
    return redirect('store:profile')

# View User's Cart (must be logged in)
# Each of a user's 'cart' only corresponds to one product since the role of the cart is to keep track
# of the products' quantity and the total price for that particular product. Thus a user buying multiple
# products will have multiple cart items

@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # Display Total Price
    cart_cost = decimal.Decimal(0)
    shipping_cost = decimal.Decimal(10) # default shipping cost is $10
    for cart_product in cart_products:
        cart_cost += cart_product.total_price

    addresses = Address.objects.filter(user=user)

    context = {
        'cart_products' : cart_products,
        'cart_cost' : cart_cost,
        'shipping_cost' : shipping_cost,
        'total_cost' : cart_cost + shipping_cost,
        'addresses' : addresses,
    }

    return render(request, 'store/cart.html', context)


# Add a new item to cart - performed from store view (must be logged in) 
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    # Check whether the Product is already in the cart or not
    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    # if in cart already, increment quantity
    if item_already_in_cart:
        item = get_object_or_404(Cart, product=product_id, user=user)
        item.quantity += 1
        item.save()
    else:
        Cart(user=user, product=product).save()

    return redirect('store:cart')

# Edit cart functions performed from cart view

# Entirely remove an existing item from cart (must be logged in)
@login_required
def remove_from_cart(request, cart_id):
    if request.method == 'GET':
        to_remove = get_object_or_404(Cart, id=cart_id)
        to_remove.delete()
        messages.success(request, "Product Removed from Cart")
    return redirect('store:cart')

# Increment the quantity of an existing item in cart (must be logged in)
@login_required
def incr_cart_item(request, cart_id):
    if request.method == 'GET':
        to_incr = get_object_or_404(Cart, id=cart_id)
        to_incr.quantity += 1
        to_incr.save()
    return redirect('store:cart')

# Decrement the quantity of an existing item in cart (must be logged in)
@login_required
def decr_cart_item(request, cart_id):
    if request.method == 'GET':
        to_decr = get_object_or_404(Cart, id=cart_id)
        # remove if only 1 left
        if to_decr.quantity == 1:
            to_decr.delete()
        else:
            to_decr.quantity -= 1
            to_decr.save()
    return redirect('store:cart')

# Checking out all products in cart
def checkout(request):
    user = request.user
    address_id = request.GET.get('address')

    address = get_object_or_404(Address, id=address_id)

    cart = Cart.objects.filter(user=user)
    for cart_item in cart:
        # Saving all products in cart to order
        Order(user=user, address=address, product=cart_item.product, quantity=cart_item.quantity).save()
        # Delete cart item after done processing it
        cart_item.delete()
    return redirect('store:orders')

# View all orders
def orders(request):
    all_orders = Order.objects.filter(user=request.user).order_by('-ordered_date')
    return render(request, 'store/orders.html', {'orders' : all_orders})

def shop(request):
    return render(request, 'store/shop.html')
    

estore/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <div class="container">
    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
        <div class="container">
        <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
            <div class="col-lg-6">
            <h1 class="h2 text-uppercase mb-0">Cart</h1>
            </div>
            <div class="col-lg-6 text-lg-right">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Cart</li>
                </ol>
            </nav>
            </div>
        </div>
        </div>
    </section>

    {% if cart_products %}
    <section class="py-5">
        <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

        {% include 'partials/_messages.html' %}

        <div class="row">
        <div class="col-lg-8 mb-4 mb-lg-0">
            <!-- CART TABLE-->
            <div class="table-responsive mb-4">
            <table class="table">
                <thead class="bg-light">
                <tr>
                    <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                    <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                    <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                    <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                    <th class="border-0" scope="col"> </th>
                </tr>
                </thead>
                <tbody>

                {% for cart_product in cart_products %}
                <tr>
                    <th class="pl-0 border-0" scope="row">
                    <div class="media align-items-center">

                        {% if cart_product.product.product_image %}
                        <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                        {% else %}
                        <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                        {% endif %}

                        <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                    </div>
                    </th>
                    <td class="align-middle border-0">
                    <p class="mb-0 small">${{cart_product.product.price}}</p>
                    </td>
                    <td class="align-middle border-0">
                    <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                        <div class="quantity">
                        <a href="{% url 'store:decr-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                        {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                        <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                        {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                        <a href="{% url 'store:incr-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                        </div>
                    </div>
                    </td>
                    <td class="align-middle border-0">
                    <p class="mb-0 small">${{cart_product.total_price|intcomma}}</p>
                    </td>
                    <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-from-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
            </div>
            <!-- CART NAV-->
            <div class="bg-light px-4 py-3">
            <div class="row align-items-center text-center">
                <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a></div>
                <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm" href="checkout.html">Procceed to checkout<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div>
            </div>
            </div>
        </div>

        <!-- ORDER TOTAL-->
        <div class="col-lg-4">
            <div class="card border-0 rounded-0 p-lg-4 bg-light">
            <div class="card-body">
                <h5 class="text-uppercase mb-4">Cart total</h5>
                <ul class="list-unstyled mb-0">
                <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">${{cart_cost|intcomma}}</span></li>
                <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Shipping Charge</strong><span class="text-muted small">+ ${{shipping_cost}}</span></li>
                <li class="border-bottom my-2"></li>
                <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>${{total_cost|intcomma}}</span></li>
                <li>

                    {% comment %} <form action="#">
                    <div class="form-group mb-0">
                        <input class="form-control" type="text" placeholder="Enter your coupon">
                        <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                    </div>
                    </form> {% endcomment %}

                </li>
                </ul>

                
                <h5 class="text-uppercase my-5">Select Shipping Address</h5>
                
                <form action="{% url 'store:checkout' %}" id="myform">

                {% if addresses %}
                    {% for address in addresses %}
                    <div class="mb-3">
                    <input type="radio" name="address" value="{{address.id}}"> <strong>Address {{forloop.counter}}</strong> <br>
                    ( {{address.location}}, {{address.street_address}}, {{address.city}}, {{address.state}} )
                    </div>
                    {% endfor %}
                {% endif %}

                <!-- Set up a container element for the button -->
                <div class="text-end" id="paypal-button-container"></div>

                {% comment %} For Cash on Delivery {% endcomment %}
                <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit"> <i class="fas fa-dollar-sign mr-2"></i>Cash on Delivery</button>

                </form>

            </div>
            </div>
        </div>
        </div>
    </section>
    
    {% else %}

        <div class="text-center py-5">
        <h3 class="mb-3">Your cart is empty.</h3>
        <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
        </div>

    {% endif %}

    </div>
{% endblock content %}

{% block payment-gateway %}
<!-- Include the PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD&disable-funding=credit"></script>

<script>
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    cost: {
                        value: '{{total_cost}}'
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                alert('Transaction completed by ' + details.payer.name.given_name + '!');
                // Savind Order in Database after Payment Success
                document.getElementById('myform').submit();
            });
        }

    }).render('#paypal-button-container');
</script>
{% endblock payment-gateway %}

estore/templates/store/index.html
{% extends 'base.html' %}
{% load static %}

      {% block content %}

      <!-- HERO SECTION-->
      <!-- <div class="video-background">
        <div class="video-wrap">
          <div id="video">
            <video id="bgvid" autoplay loop muted playsinline>
              <source src="{% static 'vid/mens-clothing-video.mp4' %}" type="video/mp4">
            </video>
          </div>
        </div>
      </div> -->

      <div class="container">
        <section class="hero pb-3 bg-cover bg-center d-flex align-items-center" style="background: url('media/img/clothing-banner.jpg');">
          <div class="container py-5">
            <div class="row px-4 px-lg-5">
              <div class="col-lg-6">
                <p class="small text-uppercase mb-2">New Inspiration 2020</p>
                <h1 class="h2 text-white text-uppercase mb-3">20% off on new season</h1><a class="btn btn-secondary" href="{% url 'store:all-categories' %}">Browse collections</a>
              </div>
            </div>
          </div>
        </section>


        <!-- CATEGORIES SECTION-->
        <section class="pt-5">
          <header class="text-center">
            <p class="small text-muted small text-uppercase mb-1">Carefully created collections</p>
            <h2 class="h5 text-uppercase mb-4">Browse our categories</h2>
          </header>
          <div class="row">
          {% if categories %}
            {% for category in categories %}

              <div class="col-md-4 mb-4 mb-md-0">
                <a class="category-item" href="{% url 'store:category-products' category.slug %}">
                  {% if category.category_image %}
                    <img class="img-fluid" src="{{ category.category_image.url }}" alt="{{ category.title }}">
                    {% else %}
                    <img class="img-fluid" src="{% static 'img/cat-img-1.jpg' %}" alt="{{ category.title }}">
                  {% endif %}
                  <strong class="category-item-title">{{ category.title }}</strong>
                </a>
              </div>
            
            {% endfor %}
          {% endif %}
          </div>
        </section>


        <!-- TRENDING PRODUCTS-->
        <section class="py-5">
          <header>
            <p class="small text-muted small text-uppercase mb-1">Made the hard way</p>
            <h2 class="h5 text-uppercase mb-4">Top trending products</h2>
          </header>
          <div class="row">

            {% if products %}
              {% for product in products %}
              
                <!-- PRODUCT-->
                <div class="col-xl-3 col-lg-4 col-sm-6">
                  <div class="product text-center">
                    <div class="position-relative mb-3">

                      <div class="badge text-white badge-"></div>
                      
                      <a class="d-block" href="{% url 'store:product-detail' product.slug %}">
                        {% if product.product_image %}
                          <img class="img-fluid w-100" src="{{ product.product_image.url }}" alt="{{product.title}}">
                        {% else %}
                          <img class="img-fluid w-100" src="{% static 'img/product-1.jpg' %}" alt="{{product.title}}">
                        {% endif %}
                      </a>

                      <div class="product-overlay">
                        <ul class="mb-0 list-inline">
                          <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-outline-dark" href="#"><i class="far fa-heart"></i></a></li>
                          <li class="list-inline-item m-0 p-0">
                            {% comment %} <a class="btn btn-sm btn-dark" href="{% url 'store:add-to-cart' %}">Add to cart</a> {% endcomment %}

                            <form action="{% url 'store:add-to-cart' %}">
                              <input type="hidden" name="prod_id" value="{{product.id}}" id="product_id">
                              <button type="submit" class="btn btn-sm btn-dark">Add to Cart</button>
                            </form>

                          </li>
                        </ul>
                      </div>
                    </div>
                    <h6> <a class="reset-anchor" href="detail.html">{{ product.title }}</a></h6>
                    <p class="small text-muted">${{product.price}}</p>
                  </div>
                </div>

              {% endfor %}
            {% endif %}

            

          </div>
        </section>


        <!-- SERVICES-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row text-center">
              <div class="col-lg-4 mb-3 mb-lg-0">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#delivery-time-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Free shipping</h6>
                      <p class="text-small mb-0 text-muted">Free shipping worlwide</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-3 mb-lg-0">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#helpline-24h-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">24 x 7 service</h6>
                      <p class="text-small mb-0 text-muted">Free shipping worlwide</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#label-tag-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Festival offer</h6>
                      <p class="text-small mb-0 text-muted">Free shipping worlwide</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>


        <!-- NEWSLETTER-->
        <section class="py-5">
          <div class="container p-0">
            <div class="row">
              <div class="col-lg-6 mb-3 mb-lg-0">
                <h5 class="text-uppercase">Let's be friends!</h5>
                <p class="text-small text-muted mb-0">Nisi nisi tempor consequat laboris nisi.</p>
              </div>
              <div class="col-lg-6">
                <form action="#">
                  <div class="input-group flex-column flex-sm-row mb-3">
                    <input class="form-control form-control-lg py-3" type="email" placeholder="Enter your email address" aria-describedby="button-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-dark btn-block" id="button-addon2" type="submit">Subscribe</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
      </div>

      {% endblock content %}